on: pull_request

name: Build and Test

jobs:
  build:
    name: Build and Test
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@master
    
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    
    - name: Test
      uses: actions/npm@master
      with:
        args: test
