on:
  release:
    types: [published]
    tags: v*
    
name: Release Plugin Version

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
 
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm test
    - run: npm build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    