on:
  release:
    types: [published]
    tags: v*
    
name: Release Plugin Version

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install
      uses: actions/npm@master
      with:
        args: install
    
    - name: Test
      uses: actions/npm@master
      with:
        args: test
    
    - name: Build Bundle
      uses: actions/npm@master
      with:
        args: build

    - name: Publish to NPM
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
